# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('feat', models.TextField(default=b'', verbose_name=b'\xe7\x89\xb9\xe5\xbe\x81\xe5\x80\xbc')),
                ('url', models.CharField(default=b'', max_length=128, verbose_name=b'\xe9\x93\xbe\xe6\x8e\xa5')),
                ('path', models.CharField(default=b'', max_length=128, verbose_name=b'\xe5\x9c\xb0\xe5\x9d\x80')),
                ('is_show', models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xbe\xe7\xa4\xba')),
            ],
            options={
                'db_table': 'tb_face',
                'verbose_name': '\u4eba\u8138\u4fe1\u606f    ',
                'verbose_name_plural': '\u4eba\u8138\u4fe1\u606f    ',
            },
        ),
        migrations.CreateModel(
            name='Famous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=30, verbose_name=b'\xe5\x90\x8d\xe5\xad\x97')),
                ('num', models.CharField(default=b'', max_length=30, verbose_name=b'\xe6\x95\xb0\xe5\xad\x97')),
                ('birthplace', models.CharField(default=b'', max_length=40, verbose_name=b'\xe5\x87\xba\xe7\x94\x9f\xe5\x9c\xb0')),
                ('birthday', models.CharField(default=b'', max_length=30, verbose_name=b'\xe7\x94\x9f\xe6\x97\xa5')),
                ('height', models.CharField(default=b'', max_length=8, verbose_name=b'\xe8\xba\xab\xe9\xab\x98')),
                ('university', models.CharField(default=b'', max_length=60, verbose_name=b'\xe5\xa4\xa7\xe5\xad\xa6')),
                ('works', models.TextField(default=b'', max_length=500, verbose_name=b'\xe4\xbd\x9c\xe5\x93\x81')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('is_show', models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xbe\xe7\xa4\xba')),
            ],
            options={
                'db_table': 'tb_famous',
                'verbose_name': '\u540d\u4eba\u4fe1\u606f    ',
                'verbose_name_plural': '\u540d\u4eba\u4fe1\u606f    ',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91ID')),
                ('external_id', models.CharField(default=b'', max_length=64, verbose_name=b'\xe5\xa4\x96\xe9\x83\xa8ID')),
                ('external_system', models.CharField(default=b'', max_length=64, verbose_name=b'\xe5\xa4\x96\xe9\x83\xa8\xe7\xb3\xbb\xe7\xbb\x9f')),
                ('name', models.CharField(default=b'', max_length=30, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
                ('file_url', models.CharField(max_length=128, verbose_name=b'\xe8\xae\xbf\xe9\x97\xae\xe5\x9c\xb0\xe5\x9d\x80')),
                ('video_format', models.CharField(default=b'', max_length=16, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe6\xa0\xbc\xe5\xbc\x8f')),
                ('size', models.CharField(default=b'', max_length=16, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe5\xa4\xa7\xe5\xb0\x8f')),
                ('video_length', models.CharField(default=b'', max_length=16, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe9\x95\xbf\xe5\xba\xa6')),
                ('file_path', models.CharField(default=b'', max_length=128, verbose_name=b'\xe5\xad\x98\xe6\x94\xbe\xe5\x9c\xb0\xe5\x9d\x80')),
                ('media_status', models.CharField(default=b'', max_length=32, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('is_show', models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xbe\xe7\xa4\xba')),
            ],
            options={
                'db_table': 'tb_media',
                'verbose_name': '\u89c6\u9891\u4fe1\u606f    ',
                'verbose_name_plural': '\u89c6\u9891\u4fe1\u606f    ',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xe4\xbb\xbb\xe5\x8a\xa1ID')),
                ('name', models.CharField(default=b'', max_length=30, verbose_name=b'\xe5\x90\x8d\xe5\xad\x97')),
                ('state', models.SmallIntegerField(choices=[(1, b'\xe5\xae\x8c\xe6\x88\x90'), (2, b'\xe6\x9c\xaa\xe5\xbc\x80\xe5\xa7\x8b'), (3, b'\xe6\xa3\x80\xe6\xb5\x8b\xe4\xb8\xad')], default=2, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('target_face_id', models.TextField(default=b'', verbose_name=b'\xe7\x9b\xae\xe6\xa0\x87\xe4\xba\xba\xe7\x89\xa9')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('is_show', models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xbe\xe7\xa4\xba')),
                ('famous_list', models.ManyToManyField(to='video.Famous')),
                ('task_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Media')),
            ],
            options={
                'db_table': 'tb_task',
                'verbose_name': '\u4efb\u52a1\u4fe1\u606f    ',
                'verbose_name_plural': '\u4efb\u52a1\u4fe1\u606f    ',
            },
        ),
        migrations.AddField(
            model_name='face',
            name='famous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Famous'),
        ),
    ]
