# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('famous_count', models.IntegerField(default=b'', verbose_name=b'\xe6\x98\x8e\xe6\x98\x9f\xe6\x80\xbb\xe6\x95\xb0')),
                ('face_count', models.IntegerField(default=b'', verbose_name=b'\xe6\x98\x8e\xe6\x98\x9f\xe5\x9b\xbe\xe7\x89\x87\xe6\x80\xbb\xe6\x95\xb0')),
                ('media_count', models.IntegerField(default=b'', verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe6\x80\xbb\xe6\x95\xb0')),
                ('task_count', models.IntegerField(default=b'', verbose_name=b'\xe4\xbb\xbb\xe5\x8a\xa1\xe6\x80\xbb\xe6\x95\xb0')),
            ],
            options={
                'db_table': 'tb_count',
                'verbose_name': '\u8ba1\u6570\u4fe1\u606f',
                'verbose_name_plural': '\u8ba1\u6570\u4fe1\u606f',
            },
        ),
    ]
