# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='progress',
            field=models.CharField(default=b'', max_length=10, verbose_name=b'\xe8\xbf\x9b\xe5\xba\xa6'),
        ),
    ]
