# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_media_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='force_url',
            field=models.CharField(default=b'', max_length=128, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe6\xba\x90\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
    ]
