# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_media_force_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='famous',
            name='type',
            field=models.SmallIntegerField(choices=[(1, b'\xe6\x98\x8e\xe6\x98\x9f'), (2, b'\xe6\x94\xbf\xe6\xb2\xbb\xe4\xba\xba\xe7\x89\xa9'), (3, b'')], default=3, verbose_name=b'\xe4\xba\xba\xe7\x89\xa9\xe5\x88\x86\xe7\xb1\xbb'),
        ),
    ]
