# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_famous_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_keyframe',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x9c\x89\xe5\x85\xb3\xe9\x94\xae\xe5\xb8\xa7'),
        ),
        migrations.AddField(
            model_name='media',
            name='keyframe_progress',
            field=models.CharField(default=b'', max_length=10, verbose_name=b'\xe5\x85\xb3\xe9\x94\xae\xe5\xb8\xa7\xe4\xbb\xbb\xe5\x8a\xa1\xe8\xbf\x9b\xe5\xba\xa6'),
        ),
        migrations.AddField(
            model_name='media',
            name='keyframe_status',
            field=models.SmallIntegerField(choices=[(1, b'\xe5\x87\x86\xe5\xa4\x87\xe6\xa3\x80\xe6\xb5\x8b'), (2, b'\xe6\xa3\x80\xe6\xb5\x8b\xe4\xb8\xad'), (3, b'\xe5\xae\x8c\xe6\x88\x90'), (4, b'')], default=4, verbose_name=b'\xe5\x85\xb3\xe9\x94\xae\xe5\xb8\xa7\xe4\xbb\xbb\xe5\x8a\xa1\xe7\x8a\xb6\xe6\x80\x81'),
        ),
        migrations.AlterField(
            model_name='famous',
            name='works',
            field=models.TextField(default=b'', verbose_name=b'\xe4\xbd\x9c\xe5\x93\x81'),
        ),
    ]
